### ISSUE TITLE
[IOS] App crash with google_mlkit_translation

### ISSUE THREAD

**Issue by longtn-imt** [flutter-ml/google_ml_kit_flutter#551]
**Crash app IOS when call function translateText(...)**

**File pubspec.yaml**
```
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  camera: any
  google_mlkit_commons: ^0.6.1
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_translation: ^0.9.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
```

**Debug console**

[MLKit][I-MLK008000] Error reading configs: Error Domain=com.google.mlkit Code=13 "Couldn't read file." UserInfo={NSLocalizedDescription=Couldn't read file., NSUnderlyingError=0x600001e9b090 {Error Domain=NSCocoaErrorDomain Code=260 "The file “remote_config.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/longtn/Library/Developer/CoreSimulator/Devices/AD7304E2-4C45-4FAA-8FEA-6A5B26B01866/data/Containers/Data/Application/CD90B1CC-410A-4ED2-B0ED-4AB86BFB7246/Library/Application Support/com.google.mlkit.remoteconfig/remote_config.json, NSUnderlyingError=0x600001e98870 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
